### ISSUE TITLE
Related links

### ISSUE THREAD

**Issue by knoxknox** [serradura/awesome-activeadmin#5]
@serradura I think that this repo should only contains related resources, could we remove (cleanup) 'Utilities' and 'StackOverflow' that are not directly connected to active-admin ?

**Comment by serradura** [comment]
@knoxknox I did this! :smile: 

I removed 'StackOverflow' section and move the utilities section to this repository [wiki](https://github.com/serradura/awesome-activeadmin/wiki).

Tks!
